# Generated by Django 4.1 on 2022-08-18 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDibyPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='Categoria:')),
                ('icon', models.CharField(max_length=100, verbose_name='Icono:')),
                ('is_available', models.BooleanField(default=True, verbose_name='Activo?')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoria de Dibujo',
                'verbose_name_plural': 'Categorias de Dibujos',
            },
        ),
        migrations.CreateModel(
            name='CategoryManualidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='Categoria:')),
                ('icon', models.CharField(max_length=100, verbose_name='Icono:')),
                ('is_available', models.BooleanField(default=True, verbose_name='Activo?')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoria de Manualidad',
                'verbose_name_plural': 'Categorias de Manualidades',
            },
        ),
        migrations.CreateModel(
            name='CategoryTarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='Categoria:')),
                ('icon', models.CharField(max_length=100, verbose_name='Icono:')),
                ('is_available', models.BooleanField(default=True, verbose_name='Activo?')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoria de Tarjeta',
                'verbose_name_plural': 'Categorias de Tarjetas',
            },
        ),
        migrations.CreateModel(
            name='CategoryTela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='Categoria:')),
                ('icon', models.CharField(max_length=100, verbose_name='Icono:')),
                ('is_available', models.BooleanField(default=True, verbose_name='Activo?')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoria de Tela',
                'verbose_name_plural': 'Categorias de Telas',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=60, verbose_name='Apellidos')),
                ('rank', models.IntegerField(verbose_name='Calificación')),
                ('description', models.TextField(max_length=200, verbose_name='Descripción:')),
                ('is_available', models.BooleanField(default=False, verbose_name='Activo?')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
            },
        ),
        migrations.CreateModel(
            name='ProductTela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='Nombre:')),
                ('slug', models.CharField(max_length=100, verbose_name='Slug:')),
                ('description', models.TextField(max_length=200, verbose_name='Descripcion:')),
                ('img', models.ImageField(upload_to='photos/products', verbose_name='Imagen:')),
                ('is_available', models.BooleanField(default=True, verbose_name='Activo?')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.categorytela')),
            ],
            options={
                'verbose_name': 'Producto Tela',
                'verbose_name_plural': 'Productos de Telas',
            },
        ),
        migrations.CreateModel(
            name='ProductTarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='Nombre:')),
                ('slug', models.CharField(max_length=100, verbose_name='Slug:')),
                ('description', models.TextField(max_length=200, verbose_name='Descripcion:')),
                ('img', models.ImageField(upload_to='photos/products', verbose_name='Imagen:')),
                ('is_available', models.BooleanField(default=True, verbose_name='Activo?')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.categorytarjeta')),
            ],
            options={
                'verbose_name': 'Producto Tarjeta',
                'verbose_name_plural': 'Productos de Tarjetas',
            },
        ),
        migrations.CreateModel(
            name='ProductManualidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='Nombre:')),
                ('slug', models.CharField(max_length=100, verbose_name='Slug:')),
                ('description', models.TextField(max_length=200, verbose_name='Descripcion:')),
                ('img', models.ImageField(upload_to='photos/products', verbose_name='Imagen:')),
                ('is_available', models.BooleanField(default=True, verbose_name='Activo?')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.categorymanualidades')),
            ],
            options={
                'verbose_name': 'Producto Manualidad',
                'verbose_name_plural': 'Productos de Manualidades',
            },
        ),
        migrations.CreateModel(
            name='ProductDibyPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='Nombre:')),
                ('slug', models.CharField(max_length=100, verbose_name='Slug:')),
                ('description', models.TextField(max_length=200, verbose_name='Descripcion:')),
                ('img', models.ImageField(upload_to='photos/products', verbose_name='Imagen:')),
                ('is_available', models.BooleanField(default=True, verbose_name='Activo?')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.categorydibypin')),
            ],
            options={
                'verbose_name': 'Producto Dibujo',
                'verbose_name_plural': 'Productos de Dibujos',
            },
        ),
    ]
