# Generated by Django 4.1 on 2022-08-22 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/products', verbose_name='Imagen')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='category.producttarjeta')),
            ],
        ),
    ]
