# Generated by Django 4.1 on 2022-08-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nombre:')),
                ('email', models.CharField(max_length=100, verbose_name='Correo:')),
                ('phone', models.CharField(max_length=10, verbose_name='Telefono:')),
                ('message', models.TextField(verbose_name='Mensaje:')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Nombre:')),
                ('category', models.CharField(choices=[('Tarjeta', 'Tarjeta'), ('Manualidad', 'Manualidad'), ('Dibujo', 'Dibujo'), ('Pintura', 'Pintura'), ('Pintura en Tela', 'Pintura en Tela')], default='Tarjeta', max_length=60, verbose_name='Categoria:')),
                ('image', models.ImageField(upload_to='photos', verbose_name='Imagen:')),
                ('is_available', models.BooleanField(default=True, verbose_name='Activo?')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
            },
        ),
    ]
